#!/bin/bash

prev=a

generatorText="I watched Avengers: Endgame."

SPOILER="Spoiler Alert!"

while ((1))
do
	if [[ -e log.txt ]]
	then
		cur=$( tail -n 1 log.txt )
		if [[ $cur != $prev ]] 
		then
			if [[ $cur == "I watched Avengers: Endgame." ]]
			then
				echo $SPOILER
				prev=$cur
			else
				echo $cur
				prev=$cur
			fi
		fi
	fi
done
